name: Site Settings and Labels
type: module
description: Provides a site settings entity for non-admin controlled settings and labels
core: 8.x
core_version_requirement: ^8 || ^9
package: Custom

# Information added by Drupal.org packaging script on 2020-01-25
version: '8.x-1.18'
project: 'site_settings'
datestamp: 1579967903
